import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  BOOTLOADER_MAGIC,
  crc32,
  decodeLightingConfig,
  decodeRequest,
  decodeResponse,
  encodeLightingConfig,
  encodeRequest,
  encodeResponse,
  FEATURE_KEYMAP,
  FEATURE_PERSISTENT_CONFIG,
  gitHashText,
  MAX_CONFIG_BLOB_LEN,
  MAX_MESSAGE_LEN,
  PROTOCOL_VERSION_MAJOR,
  PROTOCOL_VERSION_MINOR,
  ProtocolError,
  Reassembler,
  RESPONSE_HEADER_LEN,
  splitFrames,
  type CommandName,
  type LightingConfig,
  type Request,
  type Response,
  type ResponsePayload,
  type StatusName,
} from "./host-protocol";

// Golden vectors shared with the Rust codec; generated by
// crates/glove80-host-protocol/tests/golden.rs (v1.0, frozen) and
// tests/golden_v11.rs / golden_v12.rs / golden_v13.rs (minor additions).
const vectorsPath = fileURLToPath(
  new URL("../../../crates/glove80-host-protocol/vectors/host-protocol-v1.json", import.meta.url),
);
const vectorsV11Path = fileURLToPath(
  new URL("../../../crates/glove80-host-protocol/vectors/host-protocol-v1.1.json", import.meta.url),
);
const vectorsV12Path = fileURLToPath(
  new URL("../../../crates/glove80-host-protocol/vectors/host-protocol-v1.2.json", import.meta.url),
);
const vectorsV13Path = fileURLToPath(
  new URL("../../../crates/glove80-host-protocol/vectors/host-protocol-v1.3.json", import.meta.url),
);

interface MessageVector {
  name: string;
  kind: "request" | "response";
  requestId: number;
  message: Record<string, unknown>;
  hex: string;
}

interface FrameVector {
  name: string;
  sourceMessage: string;
  chunkSize: number;
  padded: boolean;
  messageHex: string;
  framesHex: string[];
}

interface ConfigVector {
  name: string;
  config: LightingConfig;
  hex: string;
}

interface InvalidConfigVector {
  name: string;
  hex: string;
  error: string;
}

interface GoldenDoc {
  protocol: { major: number; minor: number };
  messages: MessageVector[];
  frames?: FrameVector[];
  configs?: ConfigVector[];
  invalidConfigs?: InvalidConfigVector[];
}

const golden: GoldenDoc = JSON.parse(readFileSync(vectorsPath, "utf8"));
const goldenV11: GoldenDoc = JSON.parse(readFileSync(vectorsV11Path, "utf8"));
const goldenV12: GoldenDoc = JSON.parse(readFileSync(vectorsV12Path, "utf8"));
const goldenV13: GoldenDoc = JSON.parse(readFileSync(vectorsV13Path, "utf8"));

function unhex(hex: string): Uint8Array {
  expect(hex.length % 2).toBe(0);
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function toHex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** The vectors carry byte strings as `dataHex`; the runtime API uses
 * Uint8Array. Everything else matches the runtime shape directly. */
function vectorRequest(message: Record<string, unknown>): Request {
  const { dataHex, ...rest } = message as { dataHex?: string } & Record<string, unknown>;
  if (dataHex !== undefined) {
    return { ...rest, data: unhex(dataHex) } as Request;
  }
  return rest as unknown as Request;
}

function vectorResponse(requestId: number, message: Record<string, unknown>): Response {
  const payloadJson = message.payload as { type: string; dataHex?: string } & Record<
    string,
    unknown
  >;
  const { dataHex, ...payloadRest } = payloadJson;
  // The wire (and the vectors) omit feature-gated capability extensions;
  // the runtime shape carries 0 for absent fields.
  if (payloadRest.type === "capabilities") {
    payloadRest.maxConfigBlobLen ??= 0;
    payloadRest.keymapRows ??= 0;
    payloadRest.keymapCols ??= 0;
    payloadRest.maxKeymapEntriesPerOp ??= 0;
  }
  const payload = (
    dataHex !== undefined ? { ...payloadRest, data: unhex(dataHex) } : payloadRest
  ) as ResponsePayload;
  return {
    requestId,
    command: message.command as CommandName,
    status: message.status as StatusName,
    payload,
  };
}

function assertMessageVector(vector: MessageVector): void {
  if (vector.kind === "request") {
    const request = vectorRequest(vector.message);
    expect(toHex(encodeRequest(vector.requestId, request))).toBe(vector.hex);
    expect(decodeRequest(unhex(vector.hex))).toEqual({
      requestId: vector.requestId,
      request,
    });
  } else {
    const response = vectorResponse(vector.requestId, vector.message);
    expect(toHex(encodeResponse(response))).toBe(vector.hex);
    expect(decodeResponse(unhex(vector.hex))).toEqual(response);
  }
}

describe("host protocol golden vectors (v1.0, frozen)", () => {
  it("targets the codec's protocol major version", () => {
    // The v1.0 file is frozen at minor 0; the codec's minor only grows.
    expect(golden.protocol.major).toBe(PROTOCOL_VERSION_MAJOR);
    expect(golden.protocol.minor).toBe(0);
    expect(golden.protocol.minor).toBeLessThanOrEqual(PROTOCOL_VERSION_MINOR);
    expect(golden.messages.length).toBeGreaterThan(0);
    expect(golden.frames?.length).toBeGreaterThan(0);
  });

  for (const vector of golden.messages) {
    it(`encodes and decodes ${vector.name}`, () => {
      assertMessageVector(vector);
    });
  }

  for (const vector of golden.frames ?? []) {
    it(`splits and reassembles ${vector.name}`, () => {
      const message = unhex(vector.messageHex);
      const frames = splitFrames(message, vector.chunkSize, vector.padded);
      expect(frames.map(toHex)).toEqual(vector.framesHex);

      const reassembler = new Reassembler();
      vector.framesHex.forEach((frameHex, i) => {
        const result = reassembler.push(unhex(frameHex));
        if (i === vector.framesHex.length - 1) {
          expect(result).toEqual(message);
        } else {
          expect(result).toBeNull();
        }
      });
    });
  }
});

describe("host protocol golden vectors (v1.1)", () => {
  it("targets a minor the codec supports", () => {
    expect(goldenV11.protocol.major).toBe(PROTOCOL_VERSION_MAJOR);
    expect(goldenV11.protocol.minor).toBe(1);
    expect(goldenV11.protocol.minor).toBeLessThanOrEqual(PROTOCOL_VERSION_MINOR);
    expect(goldenV11.messages.length).toBeGreaterThan(0);
    expect(goldenV11.configs?.length).toBeGreaterThan(0);
    expect(goldenV11.invalidConfigs?.length).toBeGreaterThan(0);
  });

  for (const vector of goldenV11.messages) {
    it(`encodes and decodes ${vector.name}`, () => {
      assertMessageVector(vector);
    });
  }

  for (const vector of goldenV11.configs ?? []) {
    it(`round-trips config blob ${vector.name}`, () => {
      expect(toHex(encodeLightingConfig(vector.config))).toBe(vector.hex);
      expect(decodeLightingConfig(unhex(vector.hex))).toEqual(vector.config);
    });
  }

  for (const vector of goldenV11.invalidConfigs ?? []) {
    it(`rejects invalid config blob ${vector.name} (${vector.error})`, () => {
      expect(() => decodeLightingConfig(unhex(vector.hex))).toThrow(ProtocolError);
    });
  }
});

describe("host protocol golden vectors (v1.2, keymap editing)", () => {
  it("targets a minor the codec supports", () => {
    expect(goldenV12.protocol.major).toBe(PROTOCOL_VERSION_MAJOR);
    expect(goldenV12.protocol.minor).toBe(2);
    expect(goldenV12.protocol.minor).toBeLessThanOrEqual(PROTOCOL_VERSION_MINOR);
    expect(goldenV12.messages.length).toBeGreaterThan(0);
  });

  for (const vector of goldenV12.messages) {
    it(`encodes and decodes ${vector.name}`, () => {
      assertMessageVector(vector);
    });
  }
});

describe("host protocol golden vectors (v1.3, build identity)", () => {
  it("targets the codec's protocol version", () => {
    expect(goldenV13.protocol).toEqual({
      major: PROTOCOL_VERSION_MAJOR,
      minor: PROTOCOL_VERSION_MINOR,
    });
    expect(goldenV13.messages.length).toBeGreaterThan(0);
  });

  for (const vector of goldenV13.messages) {
    it(`encodes and decodes ${vector.name}`, () => {
      assertMessageVector(vector);
    });
  }
});

describe("lighting config blob codec", () => {
  const sample: LightingConfig = {
    togglePersistMask: 0x80,
    toggleInitialState: 0x81,
    records: [
      {
        activation: { kind: "always" },
        cells: [
          {
            key: 0,
            effect: { kind: "solid", r: 10, g: 20, b: 30, periodMs: 0, phaseMs: 0, dutyPercent: 0 },
          },
        ],
      },
      { activation: { kind: "layerActive", layer: 7 }, cells: [] },
      { activation: { kind: "toggle", id: 31 }, cells: [] },
    ],
  };

  it("matches the CRC-32/ISO-HDLC reference vector", () => {
    expect(crc32(new TextEncoder().encode("123456789"))).toBe(0xcbf43926);
    expect(crc32(new Uint8Array(0))).toBe(0);
  });

  it("round-trips and is byte-stable", () => {
    const bytes = encodeLightingConfig(sample);
    const decoded = decodeLightingConfig(bytes);
    expect(decoded).toEqual(sample);
    expect(toHex(encodeLightingConfig(decoded))).toBe(toHex(bytes));
  });

  it("rejects corruption and invalid fields", () => {
    const bytes = encodeLightingConfig(sample);
    const corrupt = bytes.slice();
    corrupt[bytes.length - 1] ^= 0xff;
    expect(() => decodeLightingConfig(corrupt)).toThrow("crc mismatch");
    const badMagic = bytes.slice();
    badMagic[0] = 0;
    expect(() => decodeLightingConfig(badMagic)).toThrow("bad config magic");
    expect(() => decodeLightingConfig(bytes.subarray(0, 10))).toThrow(ProtocolError);
    expect(() =>
      encodeLightingConfig({
        ...sample,
        records: [{ activation: { kind: "layerActive", layer: 8 }, cells: [] }],
      }),
    ).toThrow("out of range");
    expect(() =>
      encodeLightingConfig({
        ...sample,
        records: [
          {
            activation: { kind: "always" },
            cells: [
              sample.records[0].cells[0],
              sample.records[0].cells[0],
            ],
          },
        ],
      }),
    ).toThrow("appears twice");
  });

  it("caps the blob at MAX_CONFIG_BLOB_LEN", () => {
    const full: LightingConfig = {
      togglePersistMask: 0xffffffff,
      toggleInitialState: 0,
      records: Array.from({ length: 16 }, () => ({
        activation: { kind: "always" as const },
        cells: Array.from({ length: 40 }, (_, k) => ({
          key: k,
          effect: {
            kind: "blink" as const,
            r: 1,
            g: 2,
            b: 3,
            periodMs: 500,
            phaseMs: 0,
            dutyPercent: 50,
          },
        })),
      })),
    };
    expect(encodeLightingConfig(full).length).toBe(MAX_CONFIG_BLOB_LEN);
  });
});

describe("host protocol codec", () => {
  it("round-trips every request variant", () => {
    const requests: Request[] = [
      { command: "getCapabilities", clientMajor: 1, clientMinor: 0 },
      { command: "ping", data: Uint8Array.from([1, 2, 3]) },
      { command: "ping", data: new Uint8Array(0) },
      {
        command: "setCells",
        ttlMs: 0xffffffff,
        cells: [
          {
            key: 79,
            effect: { kind: "breathe", r: 1, g: 2, b: 3, periodMs: 65535, phaseMs: 0, dutyPercent: 0 },
          },
        ],
      },
      { command: "unsetCells", keys: [0, 40, 79] },
      { command: "clearOverlay" },
      { command: "readOverlay" },
      { command: "replaceOverlay", ttlMs: 0, cells: [] },
      { command: "getBrightness" },
      { command: "setBrightness", level: 255 },
      { command: "getToggle", id: 9 },
      { command: "setToggle", id: 9, state: true },
      { command: "configBegin", totalLen: 7148, blobCrc32: 0xdeadbeef },
      { command: "configData", offset: 1024, data: Uint8Array.from({ length: 100 }, () => 0xaa) },
      { command: "configData", offset: 0, data: new Uint8Array(0) },
      { command: "configCommit" },
      { command: "configAbort" },
      { command: "configRead", offset: 4096, maxLen: 1024 },
      { command: "getVersion" },
      { command: "keymapRead", layer: 7, startKey: 83, maxCount: 1 },
      { command: "keymapWrite", entries: [] },
      {
        command: "keymapWrite",
        entries: [
          { layer: 0, key: 0, keycode: 0x0004 },
          { layer: 7, key: 83, keycode: 0x5220 },
        ],
      },
      { command: "enterBootloader", magic: BOOTLOADER_MAGIC, target: "central" },
    ];
    for (const request of requests) {
      const bytes = encodeRequest(7, request);
      expect(decodeRequest(bytes)).toEqual({ requestId: 7, request });
    }
  });

  it("rejects malformed messages", () => {
    expect(() => decodeRequest(Uint8Array.from([0x77, 0, 0, 0]))).toThrow(ProtocolError);
    // Trailing garbage after the declared payload.
    expect(() => decodeRequest(Uint8Array.from([0x12, 1, 0, 0, 9]))).toThrow(
      "length field disagrees",
    );
    // Response flag missing.
    expect(() => decodeResponse(Uint8Array.from([0x12, 1, 0, 0, 0]))).toThrow(ProtocolError);
    // Unknown status.
    expect(() => decodeResponse(Uint8Array.from([0x92, 1, 0xee, 0, 0]))).toThrow(
      "unknown status",
    );
    // partialApply on a non-overlay command.
    expect(() => decodeResponse(Uint8Array.from([0xa0, 1, 0x05, 1, 0, 0]))).toThrow(
      "only valid on overlay writes",
    );
  });

  it("gates the capabilities extension on the persistent-config bit", () => {
    const base = {
      type: "capabilities" as const,
      protocolMajor: 1,
      protocolMinor: 1,
      ledCountLeft: 40,
      ledCountRight: 40,
      layerCapacity: 8,
      maxCellsPerOp: 80,
      effectMask: 0b111,
      overlayCellCapacity: 80,
      maxMessageLen: MAX_MESSAGE_LEN,
      featureBits: 0x3f,
      maxConfigBlobLen: 0,
      keymapRows: 0,
      keymapCols: 0,
      maxKeymapEntriesPerOp: 0,
    };
    const respond = (payload: ResponsePayload): Response => ({
      requestId: 1,
      command: "getCapabilities",
      status: "ok",
      payload,
    });
    const without = encodeResponse(respond(base));
    const withExtension = encodeResponse(
      respond({
        ...base,
        featureBits: 0x3f | FEATURE_PERSISTENT_CONFIG,
        maxConfigBlobLen: MAX_CONFIG_BLOB_LEN,
      }),
    );
    expect(withExtension.length).toBe(without.length + 4);
    expect(decodeResponse(without)).toEqual(respond(base));
    expect(decodeResponse(withExtension)).toEqual(
      respond({
        ...base,
        featureBits: 0x3f | FEATURE_PERSISTENT_CONFIG,
        maxConfigBlobLen: MAX_CONFIG_BLOB_LEN,
      }),
    );
  });

  it("gates the keymap extension on feature bit 7", () => {
    const base: ResponsePayload = {
      type: "capabilities",
      protocolMajor: 1,
      protocolMinor: 2,
      ledCountLeft: 40,
      ledCountRight: 40,
      layerCapacity: 8,
      maxCellsPerOp: 80,
      effectMask: 0b111,
      overlayCellCapacity: 80,
      maxMessageLen: MAX_MESSAGE_LEN,
      featureBits: 0x3f,
      maxConfigBlobLen: 0,
      keymapRows: 0,
      keymapCols: 0,
      maxKeymapEntriesPerOp: 0,
    };
    const respond = (payload: ResponsePayload): Response => ({
      requestId: 9,
      command: "getCapabilities",
      status: "ok",
      payload,
    });
    // Bit 7 without bit 6: the keymap extension sits directly at offset 16.
    const withKeymap = respond({
      ...base,
      featureBits: 0x3f | FEATURE_KEYMAP,
      keymapRows: 6,
      keymapCols: 14,
      maxKeymapEntriesPerOp: 84,
    });
    const without = encodeResponse(respond(base));
    const withExtension = encodeResponse(withKeymap);
    expect(withExtension.length).toBe(without.length + 4);
    expect(decodeResponse(withExtension)).toEqual(withKeymap);
  });

  it("skips capability extensions appended by newer protocol minors", () => {
    // A future minor with a hypothetical feature bit 9 appends its own
    // extension after the keymap extension; a v1.3 client must skip it, not
    // reject the handshake (PROTOCOL.md "Versioning": minor bumps are
    // additive).
    const expected: Response = {
      requestId: 7,
      command: "getCapabilities",
      status: "ok",
      payload: {
        type: "capabilities",
        protocolMajor: 1,
        protocolMinor: 4,
        ledCountLeft: 40,
        ledCountRight: 40,
        layerCapacity: 8,
        maxCellsPerOp: 80,
        effectMask: 0b111,
        overlayCellCapacity: 80,
        maxMessageLen: MAX_MESSAGE_LEN,
        featureBits: 0xff | (1 << 8) | (1 << 9),
        maxConfigBlobLen: MAX_CONFIG_BLOB_LEN,
        keymapRows: 6,
        keymapCols: 14,
        maxKeymapEntriesPerOp: 84,
      },
    };
    const withoutExtension = encodeResponse(expected);
    const futureExtension = Uint8Array.from([0xde, 0xad, 0xbe, 0xef]);
    const extended = new Uint8Array(withoutExtension.length + futureExtension.length);
    extended.set(withoutExtension);
    extended.set(futureExtension, withoutExtension.length);
    // Patch payload_len (u16 at offset 3) for the appended bytes.
    const view = new DataView(extended.buffer);
    view.setUint16(3, view.getUint16(3, true) + futureExtension.length, true);
    expect(decodeResponse(extended)).toEqual(expected);
  });

  it("round-trips config responses", () => {
    const responses: Response[] = [
      { requestId: 1, command: "configBegin", status: "ok", payload: { type: "empty" } },
      { requestId: 2, command: "configData", status: "noSession", payload: { type: "empty" } },
      { requestId: 3, command: "configData", status: "badOffset", payload: { type: "empty" } },
      {
        requestId: 4,
        command: "configCommit",
        status: "configIncomplete",
        payload: { type: "empty" },
      },
      { requestId: 5, command: "configCommit", status: "crcMismatch", payload: { type: "empty" } },
      {
        requestId: 6,
        command: "configCommit",
        status: "invalidConfig",
        payload: { type: "empty" },
      },
      {
        requestId: 7,
        command: "configRead",
        status: "ok",
        payload: { type: "configData", totalLen: 7148, data: Uint8Array.from([1, 2, 3]) },
      },
    ];
    for (const response of responses) {
      expect(decodeResponse(encodeResponse(response))).toEqual(response);
    }
    // The configData payload only pairs with configRead.
    expect(() =>
      encodeResponse({
        requestId: 8,
        command: "configCommit",
        status: "ok",
        payload: { type: "configData", totalLen: 0, data: new Uint8Array(0) },
      }),
    ).toThrow("does not match");
  });

  it("round-trips keymap and version responses and validates flags", () => {
    const central = {
      present: true,
      fwMajor: 0,
      fwMinor: 1,
      fwPatch: 0,
      gitHashHex: "3161326233633464", // "1a2b3c4d"
      dirty: false,
    };
    const neverSeen = {
      present: false,
      fwMajor: 0,
      fwMinor: 0,
      fwPatch: 0,
      gitHashHex: "0000000000000000",
      dirty: false,
    };
    const responses: Response[] = [
      {
        requestId: 1,
        command: "getVersion",
        status: "ok",
        payload: { type: "version", central, peripheral: neverSeen, halvesMismatch: false },
      },
      {
        requestId: 2,
        command: "keymapRead",
        status: "ok",
        payload: { type: "keymapActions", layer: 3, startKey: 10, keycodes: [4, 0, 0x7e1f] },
      },
      {
        requestId: 3,
        command: "keymapWrite",
        status: "ok",
        payload: { type: "keymapWritten", keycodes: [] },
      },
      { requestId: 4, command: "keymapWrite", status: "outOfRange", payload: { type: "empty" } },
    ];
    for (const response of responses) {
      expect(decodeResponse(encodeResponse(response))).toEqual(response);
    }

    expect(gitHashText(central.gitHashHex)).toBe("1a2b3c4d");
    expect(gitHashText(neverSeen.gitHashHex)).toBe("");

    // present / dirty / halves_mismatch must be 0 or 1 on the wire.
    const encoded = encodeResponse(responses[0]);
    const corrupt = encoded.slice();
    corrupt[RESPONSE_HEADER_LEN] = 2; // central present byte
    expect(() => decodeResponse(corrupt)).toThrow("must be 0 or 1");
    const badMismatch = encoded.slice();
    badMismatch[encoded.length - 1] = 7; // halves_mismatch byte
    expect(() => decodeResponse(badMismatch)).toThrow("must be 0 or 1");
  });

  it("rejects mismatched response payloads", () => {
    expect(() =>
      encodeResponse({
        requestId: 1,
        command: "ping",
        status: "ok",
        payload: { type: "brightness", level: 3 },
      }),
    ).toThrow("does not match");
    expect(() =>
      encodeResponse({
        requestId: 1,
        command: "ping",
        status: "busy",
        payload: { type: "echo", data: new Uint8Array(0) },
      }),
    ).toThrow("does not match");
  });
});

describe("host protocol frame layer", () => {
  it("enforces sequencing and restarts on sequence zero", () => {
    const message = Uint8Array.from({ length: 40 }, (_, i) => i);
    const frames = splitFrames(message, 20);
    expect(frames.length).toBe(3);

    const reassembler = new Reassembler();
    expect(reassembler.push(frames[0])).toBeNull();
    expect(() => reassembler.push(frames[2])).toThrow("expected frame sequence 1, got 2");

    // A fresh sequence-0 frame drops the incomplete message.
    expect(reassembler.push(frames[0])).toBeNull();
    const restart = splitFrames(Uint8Array.from([9]), 20);
    expect(reassembler.push(restart[0])).toEqual(Uint8Array.from([9]));
  });

  it("ignores padding via the per-frame length byte", () => {
    const [frame] = splitFrames(Uint8Array.from([5, 6]), 32, true);
    expect(frame.length).toBe(32);
    expect(new Reassembler().push(frame)).toEqual(Uint8Array.from([5, 6]));
  });

  it("rejects bad frames and oversized messages", () => {
    const reassembler = new Reassembler();
    expect(() => reassembler.push(Uint8Array.from([0]))).toThrow(ProtocolError);
    expect(() => reassembler.push(Uint8Array.from([0x80, 0]))).toThrow("zero-length");
    expect(() => reassembler.push(Uint8Array.from([0x80, 5, 1]))).toThrow(
      "shorter than declared",
    );
    expect(() => splitFrames(new Uint8Array(0), 20)).toThrow("empty message");
    expect(() => splitFrames(Uint8Array.from([1]), 2)).toThrow("below minimum");
    expect(() => splitFrames(new Uint8Array(MAX_MESSAGE_LEN), 3)).toThrow("exceeds 128 frames");
  });
});
